### ISSUE TITLE
import.sh doesn't work on OSX

### ISSUE THREAD

**Issue by avilleret** [bokub/git-history-editor#11] opened 2020-07-02 18:13 UTC
here is the terminal output : 

```

 % curl -fsSL https://git.io/import.sh | bash
base64: invalid option -- w
Usage:	base64 [-hvDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
\e[33m\e[39m

\e[32m↑\e[39m \e[1mDouble-click\e[0m to select, then \e[1mcopy/paste\e[0m it in Git History Editor\e[39m \e[32m↑\e[39m
```

**Comment by avilleret** [comment] 2020-07-02 18:15
it looks like an encoding issue of `import.sh`

**Comment by bokub** [comment] 2020-07-03 07:37
The problem is that on mac, the `-w` parameter of `base64` doesn't exist.

Thanks for your pull request, but I would prefer a command that works on every system

I've just committed something that works on both Linux and Windows. Can you try running the following command on your mac (in a git repo) and tell me if it works ?
`curl -fsSL https://git.io/import.sh | bash`

Thanks a lot

**Comment by bokub** [comment] 2020-07-03 07:38
Au fait, on peut parler en français 😊

**Comment by avilleret** [comment] 2020-07-03 13:13
> Au fait, on peut parler en français blush

haha ! mon anglais est si mauvais ? ;-)

I have some strange characters `\e[33m\e[39m` around each `echo` statement.

    \e[32m↑\e[39m \e[1mDouble-click\e[0m to select, then \e[1mcopy/paste\e[0m it in Git History Editor\e[39m \e[32m↑\e[39m

and that prevent the patch to work on OSX. Of course if I remove the extra characters it works, but it's not very convenient.
Strangely it works fine on LInux while I do have the same weird chars.
By any chance are you editing this script on Windows ? 

If the `-w` argument is not mandatory then removing it is the easiest fix.
and I liked the raw `git log -x --pretty=format:"%H*#%an*#%ae*#%at*#%s" | base64 | tr -d "\n"` instead of script because I can easily tweak the number of commits to treat (100 is too much for me :-) ) and it was more explicit to my eyes but that's only my point of view, and I can still use the raw command line instead of `import.sh`

**Comment by bokub** [comment] 2020-07-03 13:19
The 'strange' characters are for colored and bold text, if your terminal supports it:

![image](https://user-images.githubusercontent.com/17952318/86473339-073a3300-bd41-11ea-88cb-8bfcd2c7a612.png)


But I guess you're right, showing the raw command is a better option than a script to curl. If `| tr -d "\n"` works on your mac, then that's perfect, we don't need the `-w` anymore.

Can you please just confirm that `git log -100 --pretty=format:"%H*#%an*#%ae*#%at*#%s" | base64 | tr -d "\n"` works on your side ?

**Comment by avilleret** [comment] 2020-07-03 13:36
nice color and up arrow, never see them on my mac :-)

and yes the `git log -100 --pretty=format:"%H*#%an*#%ae*#%at*#%s" | base64 | tr -d "\n"` works fine on my mac

but I would add an extra `&& echo` at the end to  force a new line and make it easier to select the whole output :

    git log -100 --pretty=format:"%H*#%an*#%ae*#%at*#%s" | base64 | tr -d "\n" && echo

**Comment by bokub** [comment] 2020-07-03 13:40
All right, I'm removing that dumb script then...

Thanks a lot for your help!

**Closed as completed by bokub** 2020-07-03 13:40 UTC
